import { Button } from "std-widgets.slint";
export component Contador {
    in property <int> contador1: 0;
    callback chamando1();
    HorizontalLayout {
        Rectangle {
            width: 100px;
            height: 150px;
            background: purple;
            Text {
                text: "Contando: " + contador1;
            }
        }

        Rectangle {
            background: gray;
            Button {
                text: "click";
                clicked => {
                    root.chamando1()
                }
            }
        }
    }
}
