import { Button } from "std-widgets.slint";
import { CadastroPage } from "pages/cadastro.slint";
import { DashboardPage } from "pages/dashboard.slint";

export enum Page {
    Dashboard,
    Cadastro,
    Financeiro,
    Config
}

export component AppWindow inherits Window {
    width: 1600px;
    height: 900px;

    in property <length> largura_button: 140px;
    in property <length> tamanho_borda: 50px;

    // ==============================================================================//
    //                                       Dados Backend                           //
    // ==============================================================================//
    in property <string> total_alunos;
    in property <string> total_emDias;
    in property <string> total_debitos;
    in property <string> total_diarias;

    in-out property <Page> pagina_atual: Page.Dashboard;

    VerticalLayout {
        // ==============================================================================//
        //                                       Sidebar                                 //
        // ==============================================================================//
        Rectangle {
            //width: 100px;
            height: 100px;
            background: #1f2937;

            HorizontalLayout {
                padding: 8px;
                spacing: 6px;
                Rectangle { }

                Rectangle {
                    border-radius: tamanho_borda;
                    background: pagina_atual == Page.Dashboard ? #2563eb : #a200ff;
                    width: largura_button;

                    TouchArea {
                        clicked => {
                            pagina_atual = Page.Dashboard;
                        }
                    }

                    Text {
                        text: "Dashboard";
                        color: white;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }

                Rectangle {
                    width: largura_button;
                    border-radius: tamanho_borda;
                    background: pagina_atual == Page.Cadastro ? #2563eb : #a200ff;
                    TouchArea {
                        clicked => {
                            pagina_atual = Page.Cadastro;
                        }
                        Text {
                            text: "Cadastro";
                            color: white;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                }

                Rectangle {
                    border-radius: tamanho_borda;
                    background: pagina_atual == Page.Financeiro ? #2563eb : #a200ff;
                    width: largura_button;
                    TouchArea {
                        clicked => {
                            pagina_atual = Page.Financeiro;
                        }
                        Text {
                            text: "Financeiro";
                            color: white;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                }

                Rectangle {
                    width: largura_button;
                    border-radius: tamanho_borda;
                    background: pagina_atual == Page.Config ? #2563eb : #a200ff;
                    TouchArea {
                        clicked => {
                            pagina_atual = Page.Config;
                        }
                        Text {
                            text: "Configuração";
                            color: white;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                }

                Rectangle { }
            }
        }
        // ==============================================================================//
        //                                  Navegação entre janelas                      //
        // ==============================================================================//
        Rectangle {
            background: #f3f4f6;
            if(pagina_atual == Page.Dashboard): DashboardPage {
                total_alunos: root.total_alunos;
                total_emDias: root.total_emDias;
                total_debitos: root.total_debitos;
                total_diarias: root.total_diarias;
            }
            if (pagina_atual == Page.Cadastro): CadastroPage { }
        }
    }
}
