import { Button } from "std-widgets.slint";
import { CadastroPage } from "pages/cadastro.slint";
import { DashboardPage } from "pages/dashboard.slint";

export enum Page {
    Dashboard,
    Cadastro,
    Financeiro,
    Config
}

export component AppWindow inherits Window {
    width: 1600px;
    height: 900px;

    in property <length> largura_button: 140px;
    in property <length> tamanho_borda: 50px;

    // ==============================================================================//
    //                                       Dados Backend                           //
    // ==============================================================================//
    in property <string> total_clientes;
    in property <string> clientes_em_dia;
    in property <string> clientes_atrasados;
    in property <string> plano_diario;
    in property <string> plano_mensal;
    in property <string> plano_trimestral;
    in property <string> plano_semestral;
    in property <string> plano_anual;

    in-out property <Page> pagina_atual: Page.Dashboard;

    callback dashboard_load();

    VerticalLayout {
        // ==============================================================================//
        //                                       Sidebar                                 //
        // ==============================================================================//
        Rectangle {
            //width: 100px;
            height: 100px;
            background: #1f2937;

            HorizontalLayout {
                padding: 8px;
                spacing: 6px;
                Rectangle { }

                Rectangle {
                    border-radius: tamanho_borda;
                    background: pagina_atual == Page.Dashboard ? #2563eb : #a200ff;
                    width: largura_button;

                    TouchArea {
                        clicked => {
                            pagina_atual = Page.Dashboard;
                        }
                    }

                    Text {
                        text: "Dashboard";
                        color: white;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }

                Rectangle {
                    width: largura_button;
                    border-radius: tamanho_borda;
                    background: pagina_atual == Page.Cadastro ? #2563eb : #a200ff;
                    TouchArea {
                        clicked => {
                            pagina_atual = Page.Cadastro;
                        }
                        Text {
                            text: "Cadastro";
                            color: white;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                }

                Rectangle {
                    border-radius: tamanho_borda;
                    background: pagina_atual == Page.Financeiro ? #2563eb : #a200ff;
                    width: largura_button;
                    TouchArea {
                        clicked => {
                            pagina_atual = Page.Financeiro;
                        }
                        Text {
                            text: "Financeiro";
                            color: white;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                }

                Rectangle {
                    width: largura_button;
                    border-radius: tamanho_borda;
                    background: pagina_atual == Page.Config ? #2563eb : #a200ff;
                    TouchArea {
                        clicked => {
                            pagina_atual = Page.Config;
                        }
                        Text {
                            text: "Configuração";
                            color: white;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                }

                Rectangle { }
            }
        }
        // ==============================================================================//
        //                                  Navegação entre janelas                      //
        // ==============================================================================//
        Rectangle {
            background: #f3f4f6;
            if(pagina_atual == Page.Dashboard): DashboardPage {
                total_clientes: root.total_clientes;
                clientes_em_dia: root.clientes_em_dia;
                clientes_atrasados: root.clientes_atrasados;
                plano_diario: root.plano_diario;
                // plano_mensal: root.plano_mensal;
                // plano_trimestral: root.plano_trimestral;
                // plano_semestral: root.plano_semestral;
                // plano_anual: root.plano_anual;

                loaded => {
                    root.dashboard_load();
                }
            }

            if (pagina_atual == Page.Cadastro): CadastroPage { }
        }
    }
}
