import { GraficoComponent } from "components/grafico.slint";
import { Legendas } from "components/legenda.slint";
import { CardIcones } from "components/card_icones.slint";
import { TextEdit, LineEdit, Button } from "std-widgets.slint";
export component DashboardPage inherits Rectangle {
    background: #ffffff;
    in property <int> total_clientes;
    in property <int> clientes_em_dia;
    in property <int> clientes_atrasados;
    in property <int> plano_diario;
    in property <int> plano_mensal;
    in property <int> plano_trimestral;
    in property <int> plano_semestral;
    in property <int> plano_anual;

    in property <float> percentual_clientes_em_dia;
    in property <float> percentual_clientes_atrasados;
    in property <float> percentual_plano_diario;
    in property <float> percentual_plano_mensal;
    in property <float> percentual_plano_trimestral;
    in property <float> percentual_plano_semestral;
    in property <float> percentual_plano_anual;

    callback filtro_dashboard(string, string, string, string, string, string);

    callback loaded();
    init => {
        loaded();
    }

      // ==============================================================================//
     //                                      Card Esquerda                            //
    // ==============================================================================//
  HorizontalLayout {
        Rectangle {
            border-radius: 10px;
            background: #dfdfdf;
            width: root.width * 0.15;
            height: root.height;
            VerticalLayout {
                CardIcones {
                    dados: total_clientes;
                    dados_legenda: "Cadastrados: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url("../../assets/contact.png");
                }

                CardIcones {
                    dados: clientes_em_dia;
                    dados_legenda: "Em dias: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url("../../assets/pagos.png");
                }

                CardIcones {
                    dados: plano_diario;
                    dados_legenda: "Plano Diario: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url("../../assets/calendar_red.png");
                }

                CardIcones {
                    dados: plano_mensal;
                    dados_legenda: "Plano Mensal: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url("../../assets/calendar_green.png");
                }

                CardIcones {
                    dados: plano_trimestral;
                    dados_legenda: "Plano Trimestral: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url    ("../../assets/calendar_purple.png");
                }

                CardIcones {
                    dados: plano_semestral;
                    dados_legenda: "Plano Semestral: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url("../../assets/calendar_orange.png");
                }

                CardIcones {
                    dados: plano_anual;
                    dados_legenda: "Plano Anual: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url("../../assets/calendar_blue.png");
                }
            }
        }
        
        //
        // pilar central LAYOUT VERTICAL
        //
        VerticalLayout {
            padding-bottom: 150px;
            padding-left: 150px;
            padding-right: 150px;

            // Seletor de Data
            HorizontalLayout {
                alignment: start;
                width: root.width * 0.5;
                height: root.height * 0.1;
                VerticalLayout {
                    padding-top: 10px;
                    alignment: start;
                    Text {
                        font-size: root.width * 0.01;
                        text: "Dia:";
                    }

                    inicio_dia := LineEdit {
                        // background: red;
                        horizontal-alignment: center;
                        font-size: root.width * 0.01;
                        width: root.width * 0.035;
                        height: root.height * 0.035;
                    }
                }

                VerticalLayout {
                    padding-top: 10px;
                    alignment: start;
                    Text {
                        font-size: root.width * 0.01;
                        text: "Mes:";
                    }

                    inicio_mes := LineEdit {
                        // background: red;
                        horizontal-alignment: center;
                        font-size: root.width * 0.01;
                        width: root.width * 0.035;
                        height: root.height * 0.035;
                    }
                }

                VerticalLayout {
                    padding-top: 10px;
                    alignment: start;
                    Text {
                        font-size: root.width * 0.01;
                        text: "Ano:";
                    }

                    inicio_ano := LineEdit {
                        // background: red;
                        horizontal-alignment: center;
                        font-size: root.width * 0.01;
                        width: root.width * 0.045;
                        height: root.height * 0.035;
                    }
                }
            }

            HorizontalLayout {
                alignment: start;
                max-height: 10px;
                Text {
                    vertical-alignment: center;
                    font-size: root.width * 0.013;
                    text: "Até:";
                }
            }

            HorizontalLayout {
                alignment: start;
                width: root.width * 0.5;
                height: root.height * 0.1;
                VerticalLayout {
                    padding-top: 10px;
                    alignment: start;
                    Text {
                        font-size: root.width * 0.01;
                        text: "Dia:";
                    }

                    fim_dia := LineEdit {
                        // background: red;
                        horizontal-alignment: center;
                        font-size: root.width * 0.01;
                        width: root.width * 0.035;
                        height: root.height * 0.035;
                    }
                }

                VerticalLayout {
                    padding-top: 10px;
                    alignment: start;
                    Text {
                        font-size: root.width * 0.01;
                        text: "Mes:";
                    }

                    fim_mes := LineEdit {
                        // background: red;
                        horizontal-alignment: center;
                        font-size: root.width * 0.01;
                        width: root.width * 0.035;
                        height: root.height * 0.035;
                    }
                }

                VerticalLayout {
                    padding-top: 10px;
                    alignment: start;
                    Text {
                        font-size: root.width * 0.01;
                        text: "Ano:";
                    }

                    fim_ano := LineEdit {
                        // background: red;
                        horizontal-alignment: center;
                        font-size: root.width * 0.01;
                        width: root.width * 0.045;
                        height: root.height * 0.035;
                    }
                }

                VerticalLayout {
                    padding-top: 10px;
                    padding-left: 10px;
                    alignment: start;
                    Text {
                        text: "  ";
                        font-size: root.width * 0.01;
                    }

                    Button {
                        clicked => {
                            root.filtro_dashboard(inicio_dia.text, inicio_mes.text, inicio_ano.text, fim_dia.text, fim_mes.text, fim_ano.text);
                        }
                        width: root.width * 0.045;
                        height: root.height * 0.035;
                        text: "Filtrar";
                    }
                }
            }
            // imagem background grafico
            Rectangle {
                drop-shadow-blur: 10px;
                drop-shadow-offset-x: 1px;
                drop-shadow-offset-y: 1px;
                drop-shadow-color: rgb(129, 146, 247);
                border-radius: 10px;
                width: root.width * 0.5;
                height: root.height * 0.5;
                background: #d1042d;
                clip: true;
                Image {
                    source: @image-url("../../assets/image1.jpg");
                    width: 100%;
                    height: 100%;
                }

                Rectangle {
                    width: parent.width;
                    height: parent.height;
                    background: #0000;
                }
               // ==============================================================================//
              //                                       Grafico                                 //
             // ==============================================================================//
            HorizontalLayout {
                    spacing: 40px;
                    alignment: center;
                   
                    // diarias
                    GraficoComponent {
                        cor_base: #df2f10;
                        altura: percentual_plano_diario;
                    }
                    // mensal
                    GraficoComponent {
                        cor_base: #13c422;
                        altura: percentual_plano_mensal;
                    }
                    // trimestral
                    GraficoComponent {
                        cor_base: #820ec5;
                        altura: percentual_plano_trimestral;
                    }
                    //semestral
                    GraficoComponent {
                        cor_base: #dd7411;
                        altura: percentual_plano_semestral;
                    }
                    // anual
                    GraficoComponent {
                        cor_base: #1a79f5;
                        altura: percentual_plano_anual;
                    }
                }
            }
           //==============================================================================//
          //                                     Legendas                                 //
         //==============================================================================//
            HorizontalLayout {
                width: root.width * 0.5;
                height: root.height * 0.02;

                Legendas {
                    color: #df2f10;
                    legenda: "Diarias";
                    width: root.width * 0.071;
                    height: root.height * 0.08;
                }

                Legendas {
                    color: #13c422;
                    legenda: "Mensal";
                    width: root.width * 0.071;
                    height: root.height * 0.08;
                }

                Legendas {
                    color: #820ec5;
                    legenda: "Trimestral";
                    width: root.width * 0.071;
                    height: root.height * 0.08;
                }

                Legendas {
                    color: #dd7411;
                    legenda: "Semestral";
                    width: root.width * 0.071;
                    height: root.height * 0.08;
                }

                Legendas {
                    color: #1a79f5;
                    legenda: "Anual";
                    width: root.width * 0.071;
                    height: root.height * 0.08;
                }
            }
        }
        //==============================================================================//
       //                                 Cards direita                                //
      //==============================================================================//
        Rectangle {
            border-radius: 10px;
            background: #dfdfdf;
            width: root.width * 0.15;
            height: root.height;
            VerticalLayout {
                CardIcones {
                    dados: total_clientes;
                    dados_legenda: "Diarias R$: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url("../../assets/calendar_red.png");
                }

                CardIcones {
                    dados: clientes_em_dia;
                    dados_legenda: "Mensal R$: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url("../../assets/calendar_green.png");
                }

                CardIcones {
                    dados: plano_diario;
                    dados_legenda: "Trimestral R$: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url("../../assets/calendar_purple.png");
                }

                CardIcones {
                    dados: plano_mensal;
                    dados_legenda: "Semestral: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url("../../assets/calendar_orange.png");
                }

                CardIcones {
                    dados: plano_trimestral;
                    dados_legenda: "Anual R$: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url    ("../../assets/calendar_blue.png");
                }

                CardIcones {
                    dados: plano_trimestral;
                    dados_legenda: "Total R$: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url    ("../../assets/total.png");
                }
            }
        }
    }
}
