import { GraficoComponent } from "components/grafico.slint";
import { Legendas } from "components/legenda.slint";
import { CardIcones } from "components/card_icones.slint";
export component DashboardPage inherits Rectangle {
    background: #ffffff;
    in property <int> total_clientes;
    in property <int> clientes_em_dia;
    in property <int> clientes_atrasados;
    in property <int> plano_diario;
    in property <int> plano_mensal;
    in property <int> plano_trimestral;
    in property <int> plano_semestral;
    in property <int> plano_anual;

    in property <float> percentual_clientes_em_dia;
    in property <float> percentual_clientes_atrasados;
    in property <float> percentual_plano_diario;
    in property <float> percentual_plano_mensal;
    in property <float> percentual_plano_trimestral;
    in property <float> percentual_plano_semestral;
    in property <float> percentual_plano_anual;

    callback loaded();
    init => {
        loaded();
    }

    // ==============================================================================//
    //                                       Legendas grafico                        //
    // ==============================================================================//
  HorizontalLayout {
        Rectangle {
            background: blue;
            width: root.width * 0.15;
            height: root.height;
            VerticalLayout {
                CardIcones {
                    dados: total_clientes;
                    dados_legenda: "Total Cadastrados: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                    icon: @image-url("../../assets/alunos.png");
                }

                CardIcones {
                    dados: clientes_em_dia;
                    dados_legenda: "Em dias: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                }

                CardIcones {
                    dados: plano_diario;
                    dados_legenda: "Plano Diario: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                }

                CardIcones {
                    dados: plano_mensal;
                    dados_legenda: "Plano Mensal: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                }

                CardIcones {
                    dados: plano_trimestral;
                    dados_legenda: "Plano Trimestral: ";
                    width: parent.width;
                    height: parent.height * 0.1;
                }
            }
        }
        // imagem background grafico
        VerticalLayout {
            padding: 150px;
            Rectangle {
                drop-shadow-blur: 10px;
                drop-shadow-offset-x: 1px;
                drop-shadow-offset-y: 1px;
                drop-shadow-color: rgb(129, 146, 247);
                border-radius: 10px;
                width: root.width * 0.5;
                height: root.height * 0.5;
                background: #d1042d;
                clip: true;
                Image {
                    source: @image-url("../../assets/image1.jpg");
                    width: 100%;
                    height: 100%;
                }

                Rectangle {
                    width: parent.width;
                    height: parent.height;
                    background: #0000;
                }
            // ==============================================================================//
            //                                       Grafico                                 //
            // ==============================================================================//
            HorizontalLayout {
                    spacing: 40px;
                    alignment: center;
                    // em dias
                    GraficoComponent {
                        cor_base: #7600bb;
                        // cor_primaria: #7610bb6a;
                        // cor_secundaria: #7620bb2f;
                        // cor_terciaria: #7630bb6a;
                        altura: percentual_clientes_em_dia;
                    }
                    // debitos
                    GraficoComponent {
                        cor_base: #bb0033;
                        // cor_primaria: #00bcbb6a;
                        // cor_secundaria: #00bdbb2f;
                        // cor_terciaria: #00bebb6a;
                        altura: percentual_clientes_atrasados;
                    }
                    // diarias
                    GraficoComponent {
                        cor_base: #00bbbb;
                        // cor_primaria: #bb10596a;
                        // cor_secundaria: #bb20972f;
                        // cor_terciaria: #bb30336a;
                        altura: percentual_plano_diario;
                    }
                    // mensal
                    GraficoComponent {
                        cor_base: #60cc62;
                        // cor_primaria: #65dd626a;
                        // cor_secundaria: #70de622f;
                        // cor_terciaria: #75df626a;
                        altura: percentual_plano_mensal;
                    }
                    // trimestral
                    GraficoComponent {
                        cor_base: #ffd000;
                        // cor_primaria: #ffe000c8;
                        // cor_secundaria: #fff0006f;
                        // cor_terciaria: #fff0009b;
                        altura: percentual_plano_trimestral;
                    }
                    //semestral
                    GraficoComponent {
                        cor_base: #4c00da;
                        // cor_primaria: #4c11da6a;
                        // cor_secundaria: #4c22da2f;
                        // cor_terciaria: #4c33da6a;
                        altura: percentual_plano_semestral;
                    }
                    // anual
                    GraficoComponent {
                        cor_base: #fd7a00;
                        // cor_primaria: #fd8a006a;
                        // cor_secundaria: #fd9a002f;
                        // cor_terciaria: #fd9b006a;
                        altura: percentual_plano_anual;
                    }
                }
            }
            // Legendas abaixo do grafico
            HorizontalLayout {
                alignment: start;
                Legendas {
                    color: #7600bb;
                    legenda: "Em dias";
                }

                Legendas {
                    color: #bb0033;
                    legenda: "Em debito";
                }

                Legendas {
                    color: #00bbbb;
                    legenda: "Diarias";
                }

                Legendas {
                    color: #60cc62;
                    legenda: "Mensal";
                }

                Legendas {
                    color: #ffd000;
                    legenda: "Trimestral";
                }

                Legendas {
                    color: #4c00da;
                    legenda: "Semestral";
                }

                Legendas {
                    color: #fd7a00;
                    legenda: "Anual";
                }
            }
        }
    }
}
