import { LineEdit } from "std-widgets.slint";

export component StyledLineEdit inherits Rectangle {
    in-out property <string> text <=> input.text;
    in property <string> placeholder-text <=> input.placeholder-text;
    callback edited(string);

    height: 40px;
    background: white; // Always white so it pops
    border-radius: 6px;
    border-width: input.has-focus ? 2px : 1px;
    border-color: input.has-focus ? #2563eb : #64748b; // Stronger slate for unselected

    input := LineEdit {
        width: 100%;
        height: 100%;
        font-size: 14px;
        edited(t) => {
            root.edited(t)
        }
    }
}
