export component GraficoComponent {
    in property <float> altura: 10; // 10 = 10%

    in property <color> cor_base;
    in property <color> cor_primaria;
    in property <color> cor_secundaria;
    in property <color> cor_terciaria;

    VerticalLayout {
        alignment: end;

        Rectangle {
            width: 60px;
            height: parent.height * (altura * 0.01);
            background: cor_base;

            Rectangle {
                width: 30px;
                height: parent.height * (altura * 0.01);
                background: cor_primaria;

                Rectangle {
                    width: 15px;
                    height: parent.height * (altura * 0.01);
                    background: cor_secundaria;

                    Rectangle {
                        width: 20px;
                        height: parent.height * (altura * 0.01);
                        background: cor_terciaria;
                    }
                }
            }
        }
    }
}
