export component Legendas inherits Rectangle {
    border-radius: 5px;
    VerticalLayout {
        width: 120px;
        height: 20px;
    }
}
// }

// export component TextCustom {
//     in property <string> legenda;
//     in property <int> dados_legenda;
//     Text {
//         vertical-alignment: center;
//         horizontal-alignment: center;
//         text: legenda + dados_legenda;
//     }
// }
