export component Legendas inherits VerticalLayout {
    in property <color> color;
    in property <string> legenda;
    HorizontalLayout {
        spacing: 3px;
        padding: 10px;
        Rectangle {
            width: root.width * 0.2;
            height: root.height * 0.4;
            border-radius: 5px;
            background: color;
        }

        Text {
            font-size: root.width * 0.15;
            vertical-alignment: center;
            text: legenda;
        }
    }
}
